----- create transaction table schema -------------
CREATE TABLE transactions (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  	customer_id INT,
    transaction_date DATE,
    amount DECIMAL(10, 2)
);